[profile.default]
src = 'src'
out = 'abi'
libs = ['lib']
solc_version = "0.8.20"
evm_version = 'cancun' 
optimizer = true
optimizer_runs = 200
ast = true
build_info = true
extra_output = ["storageLayout"]
ffi = true

fs_permissions = [{ access = "read", path = "./"}, { access = "read-write", path = "./script/config/deployments.json"}]

[fuzz]
runs = 1024

[rpc_endpoints]
bob_testnet = "https://bob-sepolia.rpc.gobob.xyz/"
avalanche = "https://api.avax.network/ext/bc/C/rpc"
fuji = "https://api.avax-test.network/ext/bc/C/rpc"

[etherscan]
arbitrum = { key = "${ARBISCAN_API_KEY}", chain = 42161 }
avalanche = { key = "${SNOWTRACE_API_KEY}", chain = 43114 }
arbitrum_goerli = { key = "${ARBISCAN_API_KEY}", chain = 421613 }
fuji = { key = "${SNOWTRACE_API_KEY}", chain = 43113 }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config